### ISSUE TITLE
Quick cross build of pillar from amd64 to arm64 seems to be broken

### ISSUE THREAD

**Issue by rvs** [lf-edge/eve#71] opened 2019-06-10 03:51 UTC
**Description**

Quick cross build of pillar from amd64 to arm64 seems to be broken

**Steps to reproduce the issue:**

On amd64:

$ cd pkg/pillar
$ make GOARCH=arm64 build-docker

Sometime is desirable to simply cross-build pillar alone and then replace it inside of the image that is being build for deployment

**Comment by deitch** [comment] 2019-06-10 06:11
Yes! I have had this open for a while.

Question: do we care if we build in alpine or Debian? The reason I ask is installing the cross-compilers. In alpine, you need to download the right cross-compiler, usually from https://musl.cc but there are others. It currently doesn't work because of URL changes.

In Debian, you can do something like:

```Dockerfile
RUN dpkg --add-architecture arm64
RUN apt update
RUN apt install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
```

and get what you need. Alpine explicitly does not package up cross-compilers and says they have no intention to do so (I checked last week again).

Of course, the final image is `FROM alpine:3.8`, so it should not affect the results (need to watch out for libc and dynamically linked dependencies).

**Comment by rvs** [comment] 2019-06-10 06:52
I believe we can't avoid building in alpine on account on musl. Remember that the goal here is to get A SINGLE zedbox binary cross-built and then use image linkuxkit file stanza to replace it in the final image.

**Comment by deitch** [comment] 2019-06-10 06:59
> Remember that the goal here is to get A SINGLE zedbox binary cross-built

Yes, definitely. The only concern I would have is with libc (glibc vs must), and even then, only if it makes certain calls. I have done some projects that distribute on alpine but build on Debian, precisely because of the cross-building ease. Assuming we do statically linked (which we definitely should be doing), then that would be the only potential issue.

It is easy to test, of course. I will try to get to it.

The real issue here is the `CGO`. Without that, we don't need any of the cross-compilers, since go itself does it so well.

**Comment by rouming** [comment] 2023-02-06 15:47
@eriknordmark @deitch do we keep this or outdated? there was a PR recently https://github.com/lf-edge/eve/pull/2998 so no issues expected.

**Comment by rene** [comment] 2023-04-24 11:31
Correct @rouming and I can't reproduce this error anymore, let's close it.

**Closed by rene** 2023-04-24 11:31 UTC
