### ISSUE TITLE
Need way to manually re-trigger assets workflow

### ISSUE THREAD

**Issue by eriknordmark** [lf-edge/eve#3463] opened 2023-09-21 14:51 UTC
Running GH workflows we sometimes have a some fluke causing the build to fail.
The recent example is the 10.9.0 publish workflow where the first attempt in 
https://github.com/lf-edge/eve/actions/runs/6248955281/attempts/1 failed with 
 > [11/13] RUN go install github.com/seamia/protodot@87817c3d0a8e7af753af15508b51292e941bc7c6:
0.392 go: downloading github.com/seamia/protodot v1.0.0
191.5 go: github.com/seamia/protodot@87817c3d0a8e7af753af15508b51292e941bc7c6: github.com/seamia/protodot@v1.0.0: read "https:/proxy.golang.org/@v/v1.0.0.zip": read tcp 172.17.0.3:58460->142.250.113.207:443: read: connection reset by peer

This then triggered the asserts workflow which failed as expected due to some of the lfedge/eve:10.9.0-X-Y missing in dockerhub. 

As I re-run the publish workflow it should pass. But this will not re-trigger running the assets workflow.
I wonder if we can make that happen, or if we should add a manual trigger to the assets workflow so we can manually trigger it on e.g., the 10.9 branch.

**Comment by yash-zededa** [comment] 2023-09-26 07:09
We need the assets workflow to be triggered just on tag builds. We may create a conditional workflow call from publish.yaml that if the build is tag build trigger assets.yaml - this should ideally work, and we can provide the tag ref from publish.yaml.

**Comment by yash-zededa** [comment] 2023-10-28 06:05
Assets workflow is now being triggered for the tag builds only and seems to be working as expected.

example run: https://github.com/lf-edge/eve/actions/runs/6669781773/job/18130676048

**Comment by yash-zededa** [comment] 2023-10-28 06:06
@eriknordmark please confirm if we are good to close this.

**Comment by eriknordmark** [comment] 2023-10-28 08:52
Please do and refer to the pr which fixed it

**Comment by ybagarka1** [comment] 2023-10-28 20:54
The issue is fixed in [PR-3503](https://github.com/lf-edge/eve/pull/3503)

**Comment by yash-zededa** [comment] 2023-10-28 20:57
The issue is fixed in the [PR-3503](https://github.com/lf-edge/eve/pull/3503)

**Closed** 2023-10-28 20:57 UTC
