### ISSUE TITLE
Failed to build xen-tools

### ISSUE THREAD

**Issue by jren1** [lf-edge/eve#150] opened 2019-07-24 00:28 UTC
**Description**
Failed to build xen-tools

**Steps to reproduce the issue:**
1. Put the dev machine behind the firewall
2. export https_proxy and http_proxy
3. run:
build-tools/bin/linuxkit pkg build pkg/xen-tools

**Describe the results you received:**
make[4]: Leaving directory '/xen/tools/xcutils'
make[3]: Leaving directory '/xen/tools'
make[3]: Entering directory '/xen/tools'
make -C firmware install
make[4]: Entering directory '/xen/tools/firmware'
GIT=git /xen/tools/firmware/../../scripts/git-checkout.sh git://xenbits.xen.org/seabios.git rel-1.12.0 seabios-dir
Cloning into 'seabios-dir-remote.tmp'...
fatal: unable to connect to xenbits.xen.org:
xenbits.xen.org[0: 104.239.192.120]: errno=Operation timed out
make[4]: *** [Makefile:31: seabios-dir] Error 128
make[4]: Leaving directory '/xen/tools/firmware'
make[3]: *** [/xen/tools/../tools/Rules.mk:251: subdir-install-firmware] Error 2
make[3]: Leaving directory '/xen/tools'
make[2]: Leaving directory '/xen/tools'
make[2]: *** [/xen/tools/../tools/Rules.mk:246: subdirs-install] Error 2
make[1]: *** [Makefile:74: install] Error 2
make[1]: Leaving directory '/xen/tools'
make: *** [Makefile:127: install-tools] Error 2
The command '/bin/sh -c make && make dist' returned a non-zero code: 2
exit status 2

**Describe the results you expected:**
the alpine docker should be able to do:
git://xenbits.xen.org/seabios.git

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by jren1** [comment] 2019-07-24 00:37
All the eve pkgs are built with alpine Linux in Docker, including xen-tools. I tried to modify the pkg/xen-tools/Dockerfile to export GIT_PROXY_COMMAND to use git proxy, but it didn't work. It looks like alpine Linux doesn't support git proxy well.

Currently I have to use my personal home machine to build EVE, where there is no firewall. It will be nice  if we can build EVE behind the firewall, after all the companies will have the firewall.

**Comment by deitch** [comment] 2019-08-01 08:17
@jren1 it looks like git pulls are used throughout the Xen build process. 

Assuming we can get it to work via proxy, at least manually, we can standardize it into the `Dockerfile`. How did you set the `GIT_PROXY_COMMAND` when it didn't work?

**Comment by deitch** [comment] 2019-08-01 08:23
Just for a note for later. Assuming we can get this to work through a proxy, we have several issues to resolve:

* setting the proxy correctly in `pkg/xen-tools/Dockerfile`. The proxy command itself needs to be inside the container for it to work.
* the setting needs to be run-dependent (@jren1 uses it when he runs, I do not), so it cannot be permanently checked in, rather must be env or flag enabled
* our "caller" for `docker build` is `lkt pkg build`, which does not really support build args (see [this issue](https://github.com/linuxkit/linuxkit/issues/3394) just opened), so we cannot use build-args to pass it in

Those only come to play once we can get it running by manually setting it, waiting for @jren1 to respond to [this](https://github.com/lf-edge/eve/issues/150#issuecomment-517177469)

**Comment by deitch** [comment] 2019-09-06 10:40
@jren1 can we close this one out? We now have full support for `http_proxy`,`https_proxy`,`all_proxy`,`no_proxy` in building the builder and in building `pkg/xen-tools`. 

Please validate if it works. If yes, let us close it; if not, let's figure out what is missing and get it in.

**Comment by deitch** [comment] 2019-09-06 14:58
@jren1 confirmed by email that the proxies are, indeed, passed through.

Remaining is how to configure the git proxy script as an option.

**Comment by deitch** [comment] 2019-09-06 15:04
As I understand it, @jren1 , you have it set up to do the following:

* have a proxy script (I think you are using [this](https://github.com/openembedded/openembedded-core/blob/master/scripts/oe-git-proxy) that conforms to the git proxy requirements
* install that proxy in the image using `COPY oe-git-proxy /` in the `Dockerfile`
* Set `GIT_PROXY_COMMAND=/oe-git-proxy` env var, so that git uses that proxy script
* The git proxy script then uses `all_proxy` env var to access via the proxy

1. Is that correct?
1. Is it fair to say that if we had it set up so that if `all_proxy` was set, it would set the `GIT_PROXY_COMMAND` to that file, that it would work?

Please confirm and we will get it in.

**Comment by jren1** [comment] 2019-09-06 23:39
yes, right. To make the proxy work, 2 steps are required:
1) pass the all_proxy variable to the Dockerfile
2) copy oe-git-proxy to the docker and export GIT_PROXY_COMMAND to use oe-git-proxy

Anyway, once you cooked the patch, I can help verify.

**Comment by deitch** [comment] 2019-09-07 19:56
See #255. That should finally close this out. :-)

**Comment by jren1** [comment] 2019-09-11 02:21
Confirmed it works behind the firewall ,  good job!

**Closed** 2019-09-11 03:57 UTC
