### ISSUE TITLE
EVE does not configure statically supplied NTP server

### ISSUE THREAD

**Issue by avx-vjain** [lf-edge/eve#3140] opened 2023-04-04 01:45 UTC
Please provide information requested in the template below as much as possible.

#### Describe the bug

When a NTP server configuration is provided to EVE either in the usb.json (https://github.com/lf-edge/eve/blob/master/docs/CONFIG.md#legacy-mechanism-for-off-line-configuration-management) or via the controller in the Network configuration (https://github.com/lf-edge/eve/blob/master/api/proto/config/netcmn.proto#L86) - the EVE ignores it.

The ntpd is always pointing to pool.ntp.org.

> ps -ef | grep ntpd
 3670 root      0:00 /usr/sbin/ntpd -g -p pool.ntp.org

#### Recent release

Yes

#### How to reproduce

Steps:
Create a usb.json with static IP configuration and NTP server config and plug it into the EVE device while it is booting up. It is observed that the static IP configuration is applied but the NTP server configuration is not.

Provide the static IP configuration and NTP server config from the controller. It is observed that the static IP configuration is applied but the NTP server configuration is not.

**Comment by rene** [comment] 2023-05-18 07:34
@milan-zededa , all PRs were merged, can we close this issue?

**Comment by milan-zededa** [comment] 2023-05-18 07:46
Yes, closing..
@avx-vjain The issue is fixed in the master and in 9.4 and 8.12 LTS versions. Thanks for reporting!

**Closed by milan-zededa** 2023-05-18 07:46 UTC
Labels: bug
